GLOBAL:
  download_path: "downloads"
TG:
  api_id: ******
  api_hash: "******"
  session_name: "******"
  channels:
      - id: #without -100
        tp: 0
        name: '******'
YA:
  token: "******"
  upload_path: "******"
